version: '3'
services:
  rabbitmq:
    image: arm64v8/rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
  order-service:
    image: quiirex/order-service:v2
    ports:
      - "8000:8000"
    volumes:
      - order_data:/app/data
    # environment:
    #   - DB_HOST=db
    #   - DB_USER=order_user
    #   - DB_PASSWORD=order_password
    restart: always
  catalog-service:
    image: quiirex/catalog-service:v2
    ports:
      - "7000:7000"
    volumes:
      - catalog_data:/app/data
    environment:
      - SPRING_MONGODB_URI=mongodb+srv://Quiirex:Mh1pvc6Th23Kf990@cluster0.uer8zqi.mongodb.net/?retryWrites=true&w=majority
      - SPRING_MONGODB_DATABASE=CatalogService
      - SPRING_RABBITMQ_ADDRESSES=localhost:5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - RABBITMQ_EXCHANGE=catalog-service
      - RABBITMQ_ROUTINGKEY=zelovarenkey
    restart: always
  user-service:
    image: quiirex/user-service:v2
    ports:
      - "5000:5000"
    volumes:
      - user_data:/app/data
    # environment:
    #   - DB_HOST=db
    #   - DB_USER=user_user
    #   - DB_PASSWORD=user_password
    restart: always
volumes:
  rabbitmq_data:
  order_data:
  catalog_data:
  user_data: