version: '3'
services:
  rabbitmq:
    image: arm64v8/rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    networks:
      - my-network
  postgres:
    image: arm64v8/postgres
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - microservices/review/.env
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - my-network
  order-service:
    image: quiirex/order-service:v2
    container_name: order-service
    ports:
      - '8000:8000'
    volumes:
      - order_data:/app/data
    restart: always
    networks:
      - my-network
  catalog-service:
    image: quiirex/catalog-service:v3
    container_name: catalog-service
    ports:
      - '7000:7000'
    volumes:
      - catalog_data:/app/data
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - my-network
  user-service:
    image: quiirex/user-service:v2
    container_name: user-service
    ports:
      - '5000:5000'
    volumes:
      - user_data:/app/data
    restart: always
    networks:
      - my-network
volumes:
  rabbitmq_data:
  postgres_data:
  order_data:
  catalog_data:
  user_data:

networks:
  my-network:
    driver: bridge
