version: '3'
services:
  rabbitmq:
    image: arm64v8/rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    networks:
      - my-network
  postgres:
    image: arm64v8/postgres
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - microservices/review/.env
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - my-network
  web-api-gateway:
    image: quiirex/web-api-gateway:v2
    container_name: web-api-gateway
    ports:
      - '8080:3000'
    restart: always
    depends_on:
      - catalog-service
      - order-service
      - user-service
      - review-service
    networks:
      - my-network
  mobile-api-gateway:
    image: quiirex/mobile-api-gateway:v1
    container_name: mobile-api-gateway
    ports:
      - '4000:4000'
    restart: always
    depends_on:
      - catalog-service
      - order-service
      - user-service
      - review-service
    networks:
      - my-network
  addtocart:
    image: quiirex/addtocart:v1
    container_name: addtocart
    ports:
      - '3003:3003'
    restart: always
    depends_on:
      - web-api-gateway
    networks:
      - my-network
  authentication:
    image: quiirex/authentication:v1
    container_name: authentication
    ports:
      - '3004:3004'
    restart: always
    depends_on:
      - web-api-gateway
    networks:
      - my-network
  cart:
    image: quiirex/cart:v1
    container_name: cart
    ports:
      - '3002:3002'
    restart: always
    depends_on:
      - web-api-gateway
    networks:
      - my-network
  container:
    image: quiirex/container:v1
    container_name: container
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - web-api-gateway
    networks:
      - my-network
  productpage:
    image: quiirex/productpage:v1
    container_name: productpage
    ports:
      - '3001:3001'
    restart: always
    depends_on:
      - web-api-gateway
    networks:
      - my-network
  review-service:
    image: quiirex/review-service:v2
    container_name: review-service
    ports:
      - '50051:50051'
    volumes:
      - review_data:/app/data
    restart: always
    depends_on:
      - postgres
    networks:
      - my-network
  order-service:
    image: quiirex/order-service:v2
    container_name: order-service
    ports:
      - '8000:8000'
    volumes:
      - order_data:/app/data
    restart: always
    networks:
      - my-network
  catalog-service:
    image: quiirex/catalog-service:v3
    container_name: catalog-service
    ports:
      - '7000:7000'
    volumes:
      - catalog_data:/app/data
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - my-network
  user-service:
    image: quiirex/user-service:v2
    container_name: user-service
    ports:
      - '5000:5000'
    volumes:
      - user_data:/app/data
    restart: always
    networks:
      - my-network
volumes:
  rabbitmq_data:
  postgres_data:
  order_data:
  catalog_data:
  user_data:
  review_data:

networks:
  my-network:
    driver: bridge
