name: Unit tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
    - name: Install dependencies
      run: |
        cd microservices/user
        go mod download
        cd ../catalog
        ./gradlew assemble
    - name: Run GO unit tests
      run: |
        cd microservices/user
        go test ./test
    - name: Run Kotlin unit tests
      run: |
        cd ../catalog
        ./gradlew test
