name: Unit tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          microservices/user/go/pkg/mod
          microservices/catalog/.gradle
          microservices/order/.gradle
          microservices/review/node_modules
        key: ${{ runner.os }}-dependencies-${{ hashFiles('**/lockfiles') }}
        restore-keys: |
          ${{ runner.os }}-dependencies-
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19.x'
    - name: Install User service dependencies
      run: |
        cd microservices/user
        go mod download
    - name: Run User service unit tests
      run: |
        cd microservices/user
        go test ./test
    - name: Install Catalog service dependencies
      run: |
        cd microservices/catalog
        ./gradlew assemble
    - name: Run Catalog service unit tests
      run: |
        cd microservices/catalog
        ./gradlew test
    - name: Install Order service dependencies
      run: |
        cd microservices/order
        ./gradlew build
    - name: Run Order service unit tests
      run: |
        cd microservices/order
        ./gradlew test
    - name: Install Review service dependencies
      run: |
        cd microservices/review
        npm install
    - name: Run Review service unit tests
      run: |
        cd microservices/review
        npm run test
