name: Unit tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: corretto
        java-version: 17
    - name: Install dependencies
      run: |
        cd microservices/user
        go mod download
        cd ../catalog
        ./gradlew assemble
    - name: Run unit tests
      run: |
        cd microservices/user
        go test ./test
        cd ../catalog
        ./gradlew test
