name: Unit tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Install dependencies
      run: |
        cd microservices/user
        go mod download

    - name: Run Go unit tests
      run: |
        cd microservices/user
        go test ./test

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt@1.17'

    - name: Build and test Kotlin project
      run: |
        cd microservices/catalog
        ./gradlew test
