name: Unit tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
    - name: Install User service dependencies
      run: |
        cd microservices/user
        go mod download
    - name: Run User service unit tests
      run: |
        cd microservices/user
        go test ./test
    - name: Install Catalog service dependencies
      run: |
        cd microservices/catalog
        ./gradlew assemble
    - name: Run Catalog service unit tests
      run: |
        cd microservices/catalog
        ./gradlew test
    - name: Install Order service dependencies
      run: |
        cd microservices/order
        ./gradlew build
    - name: Run Order service unit tests
      run: |
        cd microservices/order
        ./gradlew test
